import { CheckCircle, XCircle, MinusCircle, Clock, TrendingUp } from 'lucide-react';
import type { TeamsReportData } from '../../../types';
import { cn } from '../../../utils/helpers';

interface TeamsReportCardProps {
  data: TeamsReportData;
}

const severityColors: Record<string, string> = {
  Critical: 'text-red-400 bg-red-500/10 border-red-500/30',
  High: 'text-orange-400 bg-orange-500/10 border-orange-500/30',
  Medium: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
  Low: 'text-blue-400 bg-blue-500/10 border-blue-500/30',
};

export function TeamsReportCard({ data }: TeamsReportCardProps) {
  const total = data.passed + data.failed + data.skipped;

  return (
    <div className="bg-[#1e2a3a] border border-[#2d3d4f] rounded-lg overflow-hidden max-w-md">
      {/* Purple accent bar (Teams adaptive card style) */}
      <div className="h-1 bg-purple-500" />
      <div className="p-4">
        {/* Title */}
        <div className="flex items-start justify-between mb-4">
          <div>
            <p className="text-xs text-white/50 uppercase tracking-wider font-semibold mb-1">Test Report</p>
            <p className="text-sm font-bold text-white">{data.sprintName}</p>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-white/50">
            <Clock size={12} />
            <span>{data.duration}</span>
          </div>
        </div>

        {/* Stats row */}
        <div className="grid grid-cols-3 gap-3 mb-4">
          <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-3 text-center">
            <CheckCircle size={16} className="text-green-400 mx-auto mb-1" />
            <p className="text-xl font-bold text-green-400">{data.passed}</p>
            <p className="text-xs text-white/50">Passed</p>
          </div>
          <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-3 text-center">
            <XCircle size={16} className="text-red-400 mx-auto mb-1" />
            <p className="text-xl font-bold text-red-400">{data.failed}</p>
            <p className="text-xs text-white/50">Failed</p>
          </div>
          <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3 text-center">
            <MinusCircle size={16} className="text-yellow-400 mx-auto mb-1" />
            <p className="text-xl font-bold text-yellow-400">{data.skipped}</p>
            <p className="text-xs text-white/50">Skipped</p>
          </div>
        </div>

        {/* Coverage + Pass rate */}
        <div className="flex gap-4 mb-4">
          <div className="flex-1">
            <div className="flex items-center justify-between text-xs text-white/50 mb-1">
              <span>Pass Rate</span>
              <span className="text-white font-medium">{data.passRate}%</span>
            </div>
            <div className="h-1.5 bg-white/10 rounded-full">
              <div
                className="h-full bg-green-500 rounded-full"
                style={{ width: `${data.passRate}%` }}
              />
            </div>
          </div>
          <div className="flex-1">
            <div className="flex items-center justify-between text-xs text-white/50 mb-1">
              <div className="flex items-center gap-1">
                <TrendingUp size={10} />
                <span>Coverage</span>
              </div>
              <span className="text-white font-medium">{data.coverage}%</span>
            </div>
            <div className="h-1.5 bg-white/10 rounded-full">
              <div
                className="h-full bg-blue-500 rounded-full"
                style={{ width: `${data.coverage}%` }}
              />
            </div>
          </div>
        </div>

        {/* Top failures */}
        <div>
          <p className="text-xs text-white/50 font-semibold uppercase tracking-wider mb-2">Top Failures</p>
          <div className="space-y-1.5">
            {data.topFailures.map(failure => (
              <div key={failure.name} className="flex items-center gap-2">
                <span className={cn('text-xs px-1.5 py-0.5 rounded border font-medium flex-shrink-0', severityColors[failure.severity])}>
                  {failure.severity}
                </span>
                <span className="text-xs text-white/80 truncate">{failure.name}</span>
                {failure.isBlocking && (
                  <span className="ml-auto text-xs text-red-400 flex-shrink-0 font-medium">Blocking</span>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="mt-3 pt-3 border-t border-white/10 text-xs text-white/40 text-center">
          {total} tests · Generated by Ordino Bot
        </div>
      </div>
    </div>
  );
}
