import { motion } from 'framer-motion';
import { Clock, DollarSign, Zap, TrendingUp } from 'lucide-react';
import { Card } from '../common';
import { roiMetrics } from '../../data/mockData';

export function RoiMetricsCard() {
    return (
        <Card className="col-span-1 md:col-span-2 lg:col-span-4 bg-gradient-to-r from-ordino-primary/10 to-ordino-secondary/10 border-ordino-primary/20">
            <div className="flex flex-col md:flex-row items-center justify-between gap-6 p-2">

                {/* Header Section */}
                <div className="flex-1">
                    <h3 className="text-xl font-bold text-ordino-text flex items-center gap-2">
                        <TrendingUp className="text-ordino-primary" />
                        ROI Immediacy
                    </h3>
                    <p className="text-ordino-text-muted mt-1">
                        Real-time savings generated by Ordino vs manual execution this month.
                    </p>
                </div>

                {/* Metrics Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 flex-[2]">

                    {/* Hours Saved */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.2 }}
                        className="flex flex-col items-center p-4 bg-ordino-bg rounded-lg border border-ordino-border/50 shadow-sm"
                    >
                        <div className="p-3 rounded-full bg-blue-500/10 text-blue-500 mb-2">
                            <Clock size={24} />
                        </div>
                        <span className="text-3xl font-bold text-ordino-text">
                            {roiMetrics.hoursSaved}h
                        </span>
                        <span className="text-sm text-ordino-text-muted">Engineering Hours Saved</span>
                    </motion.div>

                    {/* Cost Saved */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.3 }}
                        className="flex flex-col items-center p-4 bg-ordino-bg rounded-lg border border-ordino-border/50 shadow-sm"
                    >
                        <div className="p-3 rounded-full bg-green-500/10 text-green-500 mb-2">
                            <DollarSign size={24} />
                        </div>
                        <span className="text-3xl font-bold text-ordino-text">
                            ${(roiMetrics.costSaved / 1000).toFixed(1)}k
                        </span>
                        <span className="text-sm text-ordino-text-muted">Estimated Cost Savings</span>
                    </motion.div>

                    {/* Efficiency Gain */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.4 }}
                        className="flex flex-col items-center p-4 bg-ordino-bg rounded-lg border border-ordino-border/50 shadow-sm"
                    >
                        <div className="p-3 rounded-full bg-purple-500/10 text-purple-500 mb-2">
                            <Zap size={24} />
                        </div>
                        <span className="text-3xl font-bold text-ordino-text">
                            {roiMetrics.efficiencyGain}%
                        </span>
                        <span className="text-sm text-ordino-text-muted">Efficiency Gain</span>
                    </motion.div>

                </div>
            </div>
        </Card>
    );
}
