// Mock data for Test Failure Demo workflow

export interface FailedTestCase {
  id: string;
  name: string;
  description: string;
  errorMessage: string;
  failureTime: Date;
  releaseVersion: string;
}

export interface BugDetails {
  id: string;
  jiraKey: string;
  title: string;
  description: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low';
  affectedTestCases: string[];
  rootCause: string;
  suggestedFix: string;
  component: string;
}

export interface DeveloperNotification {
  developer: string;
  email: string;
  bugKey: string;
  message: string;
  suggestions: string[];
}

// Failed test cases from latest release
export const failedTestCases: FailedTestCase[] = [
  {
    id: 'TC-002',
    name: 'TwoFactorValidationTest',
    description: 'Verify 2FA code validation (valid code)',
    errorMessage: 'AssertionError: Expected status code 200 but got 500',
    failureTime: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    releaseVersion: 'v2.4.1',
  },
  {
    id: 'TC-005',
    name: 'LoginFlowTest',
    description: 'Verify login flow with 2FA enabled',
    errorMessage: 'TimeoutException: Element not found within 30 seconds',
    failureTime: new Date(Date.now() - 1.5 * 60 * 60 * 1000), // 1.5 hours ago
    releaseVersion: 'v2.4.1',
  },
  {
    id: 'TC-007',
    name: 'SessionTimeoutTest',
    description: 'Verify session timeout behavior',
    errorMessage: 'AssertionError: Session did not timeout as expected',
    failureTime: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
    releaseVersion: 'v2.4.1',
  },
];

// Bug details discovered by Ordino
export const bugDetails: BugDetails = {
  id: 'bug-001',
  jiraKey: 'PROJ-1234',
  title: '2FA validation endpoint returns 500 error for valid codes',
  description: 'The 2FA validation endpoint is returning a 500 Internal Server Error when processing valid authentication codes. This affects all test cases that rely on 2FA validation.',
  severity: 'Critical',
  affectedTestCases: ['TC-002', 'TC-005'],
  rootCause: 'Recent deployment introduced a null pointer exception in the 2FA validation service when handling codes generated by authenticator apps. The service is not properly handling the code format.',
  suggestedFix: '1. Add null check before processing code format\n2. Update code parsing logic to handle both SMS and authenticator app formats\n3. Add proper error handling and logging\n4. Consider adding unit tests for code format validation',
  component: 'Authentication Service',
};

// Developer notification details
export const developerNotification: DeveloperNotification = {
  developer: 'John Developer',
  email: 'john.developer@company.com',
  bugKey: 'PROJ-1234',
  message: 'A critical bug has been detected in the 2FA validation endpoint. Please review the bug details and suggested fix.',
  suggestions: [
    'Check the recent changes in AuthenticationService.validate2FACode() method',
    'Review the code format parsing logic',
    'Verify the deployment logs for any errors',
    'Test with both SMS and authenticator app codes',
  ],
};

// Chat responses for developer conversation
export const failureChatResponses: Record<string, string> = {
  'root cause': `Based on my analysis, the root cause is a null pointer exception in the 2FA validation service. The recent deployment (v2.4.1) introduced a bug where the service doesn't properly handle codes from authenticator apps.

**Root Cause:**
- The code parsing logic assumes SMS format but doesn't handle authenticator app format
- Missing null check before processing code format
- Error handling is insufficient

**Affected Components:**
- AuthenticationService.validate2FACode()
- CodeFormatParser.parse()`,
  
  'fix': `Here's my suggested fix approach:

**1. Immediate Fix:**
- Add null check before processing code format
- Update CodeFormatParser to handle both formats
- Add proper error handling

**2. Code Changes:**
\`\`\`
if (code == null || code.isEmpty()) {
    throw new ValidationException("Code cannot be null or empty");
}
String formattedCode = CodeFormatParser.parse(code, format);
\`\`\`

**3. Testing:**
- Add unit tests for both SMS and authenticator formats
- Test edge cases (null, empty, invalid format)

Would you like me to generate a more detailed fix proposal?`,
  
  'test': `To test the fix:

**1. Unit Tests:**
- Test with SMS format codes (6 digits)
- Test with authenticator app codes (6 digits, no spaces)
- Test with null/empty codes
- Test with invalid formats

**2. Integration Tests:**
- Run TC-002 (TwoFactorValidationTest)
- Run TC-005 (LoginFlowTest)
- Verify both pass with the fix

**3. Manual Testing:**
- Test login flow with 2FA enabled
- Use both SMS and authenticator app codes
- Verify error handling works correctly`,
  
  'impact': `**Impact Analysis:**

**Affected Test Cases:** 2
- TC-002: TwoFactorValidationTest
- TC-005: LoginFlowTest

**User Impact:** High
- Users cannot complete 2FA validation
- Login flow is broken for 2FA-enabled accounts
- Affects production environment

**Business Impact:**
- Critical severity bug
- Blocks user authentication
- Requires immediate fix

**Estimated Fix Time:** 2-4 hours`,
  
  'deployment': `**Deployment Considerations:**

**1. Rollback Plan:**
- Keep previous version ready for quick rollback
- Monitor error rates after deployment

**2. Monitoring:**
- Watch 2FA validation endpoint error rates
- Monitor authentication success rates
- Check application logs for exceptions

**3. Testing:**
- Deploy to staging first
- Run full test suite
- Verify both SMS and authenticator app flows

**4. Communication:**
- Notify QA team before deployment
- Prepare release notes
- Monitor user reports`,
};

export const suggestedQuestions = [
  'What is the root cause?',
  'How do I fix this?',
  'How should I test the fix?',
  'What is the impact?',
  'Deployment considerations?',
];
